### PR TITLE
Fix `add-icon-data` script

### LINKED ISSUE #12244: Broken `add-icon-data` script
Someone completely broke my `add-icon-data` script. Now it can create some incorrect data format:

### Bugs

1. SPDX license can have a link
2. `aliases` created an empty object
3. There is no `custom` license option
4. Inconsistent question mark color

### PR DESCRIPTION
**Pull request by LitoMore**
Fixes #12244

### CODE REVIEW

File: scripts/add-icon-data.js [hunk 1]
```diff
@@ -95,76 +99,95 @@ const previewHexColor = (input) => {
...
-			validate: isValidHexColor,
-			transformer: previewHexColor,
-		}),
-	),
-	source: await input({
-		message: 'What is the source URL of the icon?',
-		validate: isValidURL,
+	title: '',
+	hex: '',
+	source: '',
```
Comment (uncenter) [inline scripts/add-icon-data.js:106]: Do we need to set these initial values?

Comment (mondeja) [reply scripts/add-icon-data.js:106]: Is to make the TypeScript linter happy. The object is a `@type {IconData}` and this object needs these properties.

**Review by mondeja — APPROVED** [review]
Looks great!
