### PR TITLE
Replace 'svg-path-bounding-box' with 'svg-path-bbox'.

### LINKED ISSUE #3960: Bug in the linter? Concerning calculation of the center
### Description

I've been working on centering the icons mentioned in #3169.

Most of the icons are passing the linter on Travis without problems, but I had some problems  - especially with all the Microsoft icons.

Example: the Microsoft Excel icon
The file on `simple-icons/develop` is:

```<svg role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>Microsoft Excel icon</title><path d="M23 1.5q.41 0 .7.3.3.29.3.7v19q0 .41-.3.7-.29.3-.7.3H7q-.41 0-.7-.3-.3-.29-.3-.7V18H1q-.41 0-.7-.3-.3-.29-.3-.7V7q0-.41.3-.7Q.58 6 1 6h5V2.5q0-.41.3-.7.29-.3.7-.3zM6 13.28l1.42 2.66h2.14l-2.38-3.87 2.34-3.8H7.46l-1.3 2.4-.05.08-.04.09-.64-1.28-.66-1.29H2.59l2.27 3.82-2.48 3.85h2.16zM14.25 21v-3H7.5v3zm0-4.5v-3.75H12v3.75zm0-5.25V7.5H12v3.75zm0-5.25V3H7.5v3zm8.25 15v-3h-6.75v3zm0-4.5v-3.75h-6.75v3.75zm0-5.25V7.5h-6.75v3.75zm0-5.25V3h-6.75v3Z"/></svg>```

If I open the icon on Inkscape, it shows me, that the icon is already perfectly centered. I, of course, still click on vertical and horizontal alignment. Save the file and optimize it with https://jakearchibald.github.io/svgomg/

The resulting file looks like this:
```<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Microsoft Excel icon</title><path d="M23 1.5q.41 0 .7.3.3.29.3.7v19q0 .41-.3.7-.29.3-.7.3H7q-.41 0-.7-.3-.3-.29-.3-.7V18H1q-.41 0-.7-.3-.3-.29-.3-.7V7q0-.41.3-.7Q.58 6 1 6h5V2.5q0-.41.3-.7.29-.3.7-.3zM6 13.28l1.42 2.66h2.14l-2.38-3.87 2.34-3.8H7.46l-1.3 2.4-.05.08-.04.09-.64-1.28-.66-1.29H2.59l2.27 3.82-2.48 3.85h2.16zM14.25 21v-3H7.5v3zm0-4.5v-3.75H12v3.75zm0-5.25V7.5H12v3.75zm0-5.25V3H7.5v3zm8.25 15v-3h-6.75v3zm0-4.5v-3.75h-6.75v3.75zm0-5.25V7.5h-6.75v3.75zm0-5.25V3h-6.75v3z"/></svg>```

Which is the SAME path as the original file (except for the "Z" at the end of the path).

Pushing the commit, Travis tells me that the linter failed:
```
x icons/microsoftexcel.svg
  x icon-centered <path> must be centered at (12, 12); the center is currently 
                  (12, 12.135)
```

Unfortunately I'm not familiar with JavaScript, so I can't check the implementation of the linter.
But as I'm familiar with Python, I've calculated the center myself with this library: https://pypi.org/project/svgpathtools

For the original `microsoftexcel.svg` file on `simple-icons/develop` I get the following:
```
x_min: 5.551115123125783e-17 (so pretty much equal to 0)
x_max: 24.0
y_min: 1.5
y_max: 22.5
```

Calculating the center with `x_center = (x_max + x_min)/2` and `y_center = (y_max + y_min)/2` I get the following:
```
x_center: 12.0
y_center: 12.0
```

(I guess the 5.55e-17 were just rounded by Python during float point calculation, but that shouldn't matter anyway, because e-17 is way less than the precision tolerance of 0.001)

So the original icon is already centered. That's why after processing the original file with Inkscape and SVGOMG there aren't any changes.

Let me know what you think. :)

### PR DESCRIPTION
**Pull request by mondeja**
**Issue:** Closes #3960

Following the discussion in #3960, there is a bug in the linter which makes that icons with `Q` or `T` (and some with `C`) commands in their paths has not been linted good because of a bug in `svg-path-bounding-box`. The also existed in `svg-path-bbox`, so I have solved there and used it to replace `svg-path-bounding-box`.

The list of ignored icons must be updated. I've removed all the icons in the `.svglint-ignored.json` file so we can check those icons that have been raising false positives and those which needs to be removed from the list. I propose to:

- Check those icons corrected by @fbernhart for false positives.
- Compare the list in #3169 with [those failed in this job](https://travis-ci.com/github/mondeja/simple-icons/jobs/444048629) to make sure that we are making things correctly this time.

The good news are that seems to be less icons to correct, but not a lot.

### CODE REVIEW

File: .svglintrc.js [hunk 1]
```diff
@@ -145,11 +145,11 @@ module.exports = {
               return;
             }
 
-            const bounds = getBounds(iconPath);
+            const bbox = svgPathBbox(iconPath);
```
Comment (service-paradis) [inline .svglintrc.js:148]: A matter of preference, but would be clearer destructuring to something like:
```js
const [minX, maxX, minY, maxY] = svgPathBbox(iconPath);
```

**Comment by fbernhart** [comment]
Thanks for the quick fix!

As soon as this gets merged, I'll push "my" failed icons again. Hopefully then they will pass. 😊

File: .svglintrc.js (hunk 1 above)
Comment (mondeja) [reply .svglintrc.js]: I agree, it's done :+1:

**Comment by mondeja** [comment]
I will post the new #3169 list here and update the `.svglint-ignored.json` file in this pull as soon as possible.

**Comment by mondeja** [comment]
# Difference of icons between implementations

## Icons that should no longer be corrected

### arxiv.svg

```svg
M20.7 15.404l-1.894-4.967h1.411l1.39 3.582 1.379-3.582h.96l-1.92 4.967zM16.298 9.6V8.48h1.34V9.6zm0 5.808v-4.971h1.34v4.967zm-6.965-.003l2.146-3.3L9.43 8.707h1.627l1.364 2.254L13.9 8.707h1.12l-2.046 3.156 2.126 3.537h-1.622l-1.45-2.4-1.557 2.4H9.333zm-3.346 0v-4.968h1.338v.937c.344-.7.875-1.051 1.585-1.051a1.401 1.401 0 01.248.026v1.194a1.6 1.6 0 00-.53-.102c-.537 0-.968.267-1.303.8v3.164zm-3.028-.536q-.664.65-1.437.65a1.473 1.473 0 01-1.06-.398 1.376 1.376 0 01-.406-1.03 1.45 1.45 0 01.659-1.271q.657-.447 1.884-.448h.355v-.453q0-.772-.88-.772a3.305 3.305 0 00-1.587.443v-.922a5.016 5.016 0 011.808-.345q1.953 0 1.951 1.55v2.206c0 .39.123.58.376.58a.8.8 0 00.174-.02l.032.751a2.745 2.745 0 01-.751.13c-.552 0-.902-.216-1.06-.65h-.054zm0-.72v-1.01h-.32c-.866 0-1.297.274-1.297.815a.64.64 0 00.64.648c.329.004.647-.15.977-.453z
```

- Open pull request: #3973

- Commands in path:
  - q: YES
  - Q: NO
  - t: NO
  - T: NO
  - c: YES
  - C: NO
- `svg-path-bounding-box`:
  - minX: 0.05495008158100078
  - maxX: 23.946000000000005
  - minY: 7.594038058172477
  - maxY: 15.52
  - centerX: 12
  - centerY: 11.557
- `svg-path-bbox`:
  - minX: 0.05495008158100078
  - maxX: 23.946000000000005
  - minY: 8.48
  - maxY: 15.52
  - centerX: 12
  - centerY: 12

+ `svgpathtools`

```
Traceback (most recent call last):
  File "svgpathtools-bbox.py", line 6, in <module>
    path = parse_path(sys.argv[1])
  File "/usr/local/lib/python3.8/dist-packages/svgpathtools/parser.py", line 15, in parse_path
    return Path(pathdef, current_pos=current_pos, tree_element=tree_element)
  File "/usr/local/lib/python3.8/dist-packages/svgpathtools/path.py", line 2274, in __init__
    self._parse_path(segments[0], current_pos)
  File "/usr/local/lib/python3.8/dist-packages/svgpathtools/path.py", line 3076, in _parse_path
    end = float(elements.pop()) + float(elements.pop()) * 1j
ValueError: could not convert string to float: 'v'
```

+ `github.com/kpym/SVGPathy`
  + minX: 0.0549501
  + maxX: 23.946
  + minY: 8.48
  + maxY: 15.52
  + centerX: 12
  + centerY: 12

### emlakjet.svg

```svg
M15.65 16.105v-.24a3.543 3.543 0 00-1.267-2.471c-.724-.663-1.69-.965-2.655-.904-1.87.12-3.378 1.747-3.378 3.615 0 .784.12 1.567.422 2.471H4.55V6.946l7.42-5.123 7.482 5.122v11.692h-4.223c.18-.663.422-1.688.422-2.532m5.068-10.244L12.452.136c-.301-.181-.663-.181-.905 0L3.222 5.86c-.242.12-.362.361-.362.663V19.48c0 .482.362.844.844.844H9.92a.824.824 0 00.844-.844c0-.06 0-.18-.06-.24l-.06-.182c-.302-.723-.664-1.627-.664-2.53v-.182c-.06-.542.12-1.084.482-1.446a2.095 2.095 0 011.388-.723c.543-.06 1.026.12 1.448.482.422.362.664.844.724 1.386v.18c.06 1.206-.724 2.954-.845 3.135l-1.146 2.17-.18-.362c-.122-.181-.302-.362-.483-.422-.182-.06-.423-.06-.604.06-.18.12-.362.301-.422.482s-.06.422.06.603l.905 1.687c.121.241.423.422.724.422.302 0 .604-.18.724-.422l1.81-3.375h5.732a.824.824 0 00.844-.843V6.524c-.06-.302-.18-.543-.422-.663
```

- Commands in path:
  - q: NO
  - Q: NO
  - t: NO
  - T: NO
  - c: YES
  - C: NO
- `svg-path-bounding-box`:
  - minX: 2.86
  - maxX: 21.141225154422205
  - minY: 0.136
  - maxY: 24.000000000000004
  - centerX: 12.001
  - centerY: 12.068
- `svg-path-bbox`:
  - minX: 2.86
  - maxX: 21.141225154422205
  - minY: 0.0002500000000000141
  - maxY: 24.000000000000004
  - centerX: 12.001
  - centerY: 12

+ `svgpathtools`

```
Traceback (most recent call last):
  File "svgpathtools-bbox.py", line 6, in <module>
    path = parse_path(sys.argv[1])
  File "/usr/local/lib/python3.8/dist-packages/svgpathtools/parser.py", line 15, in parse_path
    return Path(pathdef, current_pos=current_pos, tree_element=tree_element)
  File "/usr/local/lib/python3.8/dist-packages/svgpathtools/path.py", line 2274, in __init__
    self._parse_path(segments[0], current_pos)
  File "/usr/local/lib/python3.8/dist-packages/svgpathtools/path.py", line 3076, in _parse_path
    end = float(elements.pop()) + float(elements.pop()) * 1j
ValueError: could not convert string to float: 'c'
```

+ `github.com/kpym/SVGPathy`
  + minX: 2.86
  + maxX: 21.1412252
  + minY: 0.00025
  + maxY: 24
  + centerX: 12.001
  + centerY: 12

### microsoftexcel.svg

```svg
M23 1.5q.41 0 .7.3.3.29.3.7v19q0 .41-.3.7-.29.3-.7.3H7q-.41 0-.7-.3-.3-.29-.3-.7V18H1q-.41 0-.7-.3-.3-.29-.3-.7V7q0-.41.3-.7Q.58 6 1 6h5V2.5q0-.41.3-.7.29-.3.7-.3zM6 13.28l1.42 2.66h2.14l-2.38-3.87 2.34-3.8H7.46l-1.3 2.4-.05.08-.04.09-.64-1.28-.66-1.29H2.59l2.27 3.82-2.48 3.85h2.16zM14.25 21v-3H7.5v3zm0-4.5v-3.75H12v3.75zm0-5.25V7.5H12v3.75zm0-5.25V3H7.5v3zm8.25 15v-3h-6.75v3zm0-4.5v-3.75h-6.75v3.75zm0-5.25V7.5h-6.75v3.75zm0-5.25V3h-6.75v3Z
```

- Open pull request: #3915

- Commands in path:
  - q: YES
  - Q: YES
  - t: NO
  - T: NO
  - c: NO
  - C: NO
- `svg-path-bounding-box`:
  - minX: 5.551115123125783e-17
  - maxX: 24
  - minY: 1.5
  - maxY: 22.769499273762435
  - centerX: 12
  - centerY: 12.135
- `svg-path-bbox`:
  - minX: 5.551115123125783e-17
  - maxX: 24
  - minY: 1.5
  - maxY: 22.5
  - centerX: 12
  - centerY: 12

+ `svgpathtools`
  + minX: 5.551115123125783e-17
  + maxX: 24.0
  + minY: 1.5
  + maxY: 22.5
  + centerX: 12.0
  + centerY: 12.0
+ `github.com/kpym/SVGPathy`
  + minX: 0
  + maxX: 24
  + minY: 1.5
  + maxY: 22.5
  + centerX: 12
  + centerY: 12

### microsoftexchange.svg

```svg
M24 7.875q0 .293-.117.58t-.317.486L20.496 12l3.07 3.059q.2.199.317.486.117.287.117.58V21q0 .316-.117.586-.117.27-.322.475-.206.205-.475.322-.27.117-.586.117h-4.875q-.293 0-.58-.117t-.486-.317l-3.059-3.07-3.059 3.07q-.199.2-.486.317-.287.117-.58.117H4.5q-.316 0-.586-.117-.27-.117-.475-.322-.205-.206-.322-.475Q3 21.316 3 21v-3H.996q-.41 0-.703-.293T0 17.004V6.996q0-.41.293-.703T.996 6H3V3q0-.316.117-.586.117-.27.322-.475.206-.205.475-.322.27-.117.586-.117h4.875q.293 0 .58.117t.486.317l3.059 3.07 3.059-3.07q.199-.2.486-.317.287-.117.58-.117H22.5q.316 0 .586.117.27.117.475.322.205.206.322.475Q24 2.684 24 3zM4.5 3v3h6.504q.41 0 .703.293t.293.703V5.625L9.375 3zM3.375 15.938h5.25v-1.583h-3.41v-1.593h3.047V11.18H5.215V9.656H8.46V8.062H3.375zm19.125.187L19.875 13.5h-3.691q-.247 0-.463.094-.217.094-.375.252-.159.158-.252.375-.094.216-.094.463v3.691L17.625 21H22.5zm0-8.25V3h-4.875L13.5 7.125v2.191q0 .774-.404 1.424-.405.65-1.096.99v5.274q0 .41-.293.703t-.703.293H4.5v3h4.875l4.125-4.125v-2.191q0-.563.21-1.05.212-.486.575-.849t.85-.574Q15.62 12 16.184 12h2.191Z
```

- Open pull request: #3916

- Commands in path:
  - q: YES
  - Q: YES
  - t: YES
  - T: YES
  - c: NO
  - C: NO
- `svg-path-bounding-box`:
  - minX: 0
  - maxX: 24
  - minY: 1.4999999999999998
  - maxY: 22.67233909145166
  - centerX: 12
  - centerY: 12.086
- `svg-path-bbox`:
  - minX: 0
  - maxX: 24
  - minY: 1.4999999999999998
  - maxY: 22.5
  - centerX: 12
  - centerY: 12

+ `svgpathtools`
  + minX: 0.0
  + maxX: 24.0
  + minY: 1.4999999999999998
  + maxY: 22.5
  + centerX: 12.0
  + centerY: 12.0
+ `github.com/kpym/SVGPathy`
  + minX: 0
  + maxX: 24
  + minY: 1.5
  + maxY: 22.5
  + centerX: 12
  + centerY: 12

### microsoftonedrive.svg

```svg
M19.453 9.95q.961.058 1.787.468.826.41 1.442 1.066.615.657.966 1.512.352.856.352 1.816 0 1.008-.387 1.893-.386.885-1.049 1.547-.662.662-1.546 1.049-.885.387-1.893.387H6q-1.242 0-2.332-.475-1.09-.475-1.904-1.29-.815-.814-1.29-1.903Q0 14.93 0 13.688q0-.985.31-1.887.311-.903.862-1.658.55-.756 1.324-1.325.774-.568 1.711-.861.434-.129.85-.187.416-.06.861-.082h.012q.515-.786 1.207-1.413.691-.627 1.5-1.066.808-.44 1.705-.668.896-.229 1.845-.229 1.278 0 2.456.417 1.177.416 2.144 1.16.967.744 1.658 1.78.692 1.038 1.008 2.28zm-7.265-4.137q-1.325 0-2.52.544-1.195.545-2.04 1.565.446.117.85.299.405.181.792.416l4.78 2.86 2.731-1.15q.27-.117.545-.204.276-.088.58-.147-.293-.937-.855-1.705-.563-.768-1.319-1.318-.755-.551-1.658-.856-.902-.304-1.886-.304zM2.414 16.395l9.914-4.184-3.832-2.297q-.586-.351-1.23-.539-.645-.188-1.325-.188-.914 0-1.722.364-.809.363-1.412.978-.604.616-.955 1.436-.352.82-.352 1.723 0 .703.234 1.423.235.721.68 1.284zm16.711 1.793q.563 0 1.078-.176.516-.176.961-.516l-7.23-4.324-10.301 4.336q.527.328 1.13.504.604.175 1.237.175zm3.012-1.852q.363-.727.363-1.523 0-.774-.293-1.407t-.791-1.072q-.498-.44-1.166-.68-.668-.24-1.406-.24-.422 0-.838.1t-.815.252q-.398.152-.785.334-.386.181-.761.345Z
```

- Open pull request: #3917

- Commands in path:
  - q: YES
  - Q: YES
  - t: YES
  - T: NO
  - c: NO
  - C: NO
- `svg-path-bounding-box`:
  - minX: 0
  - maxX: 24
  - minY: 4.312000000000001
  - maxY: 19.99655236943747
  - centerX: 12
  - centerY: 12.154
- `svg-path-bbox`:
  - minX: 0
  - maxX: 24
  - minY: 4.312000000000001
  - maxY: 19.688000000000002
  - centerX: 12
  - centerY: 12

+ `svgpathtools`
  + minX: 0.0
  + maxX: 24.0
  + minY: 4.312000000000001
  + maxY: 19.688000000000002
  + centerX: 12.0
  + centerY: 12.0
+ `github.com/kpym/SVGPathy`
  + minX: 0
  + maxX: 24
  + minY: 4.312
  + maxY: 19.688
  + centerX: 12
  + centerY: 12


### microsoftonenote.svg

```svg
M23 1.5Q23.41 1.5 23.7 1.8 24 2.09 24 2.5V21.5Q24 21.91 23.7 22.2 23.41 22.5 23 22.5H7Q6.59 22.5 6.3 22.2 6 21.91 6 21.5V18H1Q0.59 18 0.3 17.7 0 17.41 0 17V7Q0 6.59 0.3 6.3 0.58 6 1 6H6V2.5Q6 2.09 6.3 1.8 6.59 1.5 7 1.5ZM4.56 11 7.39 15.93H9.18V8.07H7.44V13.1L4.71 8.07H2.82V15.93H4.56ZM22.5 21V18H19.5V21ZM22.5 16.5V13.5H19.5V16.5ZM22.5 12V9H19.5V12ZM22.5 7.5V3H7.5V6H11Q11.41 6 11.7 6.3 12 6.59 12 7V17Q12 17.41 11.7 17.7 11.41 18 11 18H7.5V21H18V7.5Z
```

- Open pull request: #3919

- Commands in path:
  - q: NO
  - Q: YES
  - t: NO
  - T: NO
  - c: NO
  - C: NO
- `svg-path-bounding-box`:
  - minX: 0
  - maxX: 24
  - minY: 1.5
  - maxY: 22.769499273762435
  - centerX: 12
  - centerY: 12.135
- `svg-path-bbox`:
  - minX: 0
  - maxX: 24
  - minY: 1.5
  - maxY: 22.5
  - centerX: 12
  - centerY: 12

+ `svgpathtools`
  + minX: 0.0
  + maxX: 24.0
  + minY: 1.5
  + maxY: 22.5
  + centerX: 12.0
  + centerY: 12.0
+ `github.com/kpym/SVGPathy`
  + minX: 0
  + maxX: 24
  + minY: 1.5
  + maxY: 22.5
  + centerX: 12
  + centerY: 12

### microsoftoutlook.svg

```svg
M7.88 12.04q0 .45-.11.87-.1.41-.33.74-.22.33-.58.52-.37.2-.87.2t-.85-.2q-.35-.21-.57-.55-.22-.33-.33-.75-.1-.42-.1-.86t.1-.87q.1-.43.34-.76.22-.34.59-.54.36-.2.87-.2t.86.2q.35.21.57.55.22.34.31.77.1.43.1.88zM24 12v9.38q0 .46-.33.8-.33.32-.8.32H7.13q-.46 0-.8-.33-.32-.33-.32-.8V18H1q-.41 0-.7-.3-.3-.29-.3-.7V7q0-.41.3-.7Q.58 6 1 6h6.5V2.55q0-.44.3-.75.3-.3.75-.3h12.9q.44 0 .75.3.3.3.3.75V10.85l1.24.72h.01q.1.07.18.18.07.12.07.25zm-6-8.25v3h3v-3zm0 4.5v3h3v-3zm0 4.5v1.83l3.05-1.83zm-5.25-9v3h3.75v-3zm0 4.5v3h3.75v-3zm0 4.5v2.03l2.41 1.5 1.34-.8v-2.73zM9 3.75V6h2l.13.01.12.04v-2.3zM5.98 15.98q.9 0 1.6-.3.7-.32 1.19-.86.48-.55.73-1.28.25-.74.25-1.61 0-.83-.25-1.55-.24-.71-.71-1.24t-1.15-.83q-.68-.3-1.55-.3-.92 0-1.64.3-.71.3-1.2.85-.5.54-.75 1.3-.25.74-.25 1.63 0 .85.26 1.56.26.72.74 1.23.48.52 1.17.81.69.3 1.56.3zM7.5 21h12.39L12 16.08V17q0 .41-.3.7-.29.3-.7.3H7.5zm15-.13v-7.24l-5.9 3.54Z
```

- Open pull request: #3918

- Commands in path:
  - q: YES
  - Q: YES
  - t: YES
  - T: NO
  - c: NO
  - C: NO
- `svg-path-bounding-box`:
  - minX: 5.551115123125783e-17
  - maxX: 24.000000000000004
  - minY: 1.4999999999999998
  - maxY: 22.727227619294418
  - centerX: 12
  - centerY: 12.114
- `svg-path-bbox`:
  - minX: 5.551115123125783e-17
  - maxX: 24.000000000000004
  - minY: 1.4999999999999998
  - maxY: 22.500000000000004
  - centerX: 12
  - centerY: 12

+ `svgpathtools`
  + minX: 5.551115123125783e-17
  + maxX: 24.000000000000004
  + minY: 1.4999999999999998
  + maxY: 22.500000000000004
  + centerX: 12.0
  + centerY: 12.0
+ `github.com/kpym/SVGPathy`
  + minX: 0
  + maxX: 24
  + minY: 1.5
  + maxY: 22.5
  + centerX: 12
  + centerY: 12


### microsoftword.svg

```svg
M23.004 1.5q.41 0 .703.293t.293.703v19.008q0 .41-.293.703t-.703.293H6.996q-.41 0-.703-.293T6 21.504V18H.996q-.41 0-.703-.293T0 17.004V6.996q0-.41.293-.703T.996 6H6V2.496q0-.41.293-.703t.703-.293zM6.035 11.203l1.442 4.735h1.64l1.57-7.876H9.036l-.937 4.653-1.325-4.5H5.38l-1.406 4.523-.938-4.675H1.312l1.57 7.874h1.641zM22.5 21v-3h-15v3zm0-4.5v-3.75H12v3.75zm0-5.25V7.5H12v3.75zm0-5.25V3h-15v3Z
```

- Open pull request: #3920

- Commands in path:
  - q: YES
  - Q: NO
  - t: YES
  - T: YES
  - c: NO
  - C: NO
- `svg-path-bounding-box`:
  - minX: 0
  - maxX: 24
  - minY: 1.5
  - maxY: 22.772661142370712
  - centerX: 12
  - centerY: 12.136
- `svg-path-bbox`:
  - minX: 0
  - maxX: 24
  - minY: 1.5
  - maxY: 22.499999999999996
  - centerX: 12
  - centerY: 12

+ `svgpathtools`
  + minX: 0.0
  + maxX: 24.0
  + minY: 1.5
  + maxY: 22.499999999999996
  + centerX: 12.0
  + centerY: 12.0
+ `github.com/kpym/SVGPathy`
  + minX: 0
  + maxX: 24
  + minY: 1.5
  + maxY: 22.5
  + centerX: 12
  + centerY: 12


### pre-commit.svg

```svg
M23.355 10.444L13.556.645a2.2 2.2 0 0 0-3.112 0L.645 10.444a2.201 2.201 0 0 0 0 3.112l9.799 9.799a2.201 2.201 0 0 0 3.112 0l9.799-9.799a2.2 2.2 0 0 0 0-3.112zm-1.657 2.918l-8.337 8.337a1.922 1.922 0 0 1-1.362.563c-.493 0-.986-.188-1.362-.563L2.3 13.362A1.92 1.92 0 0 1 1.738 12c0-.514.2-.998.564-1.362l8.337-8.337c.363-.363.847-.563 1.361-.563s.998.2 1.362.564l8.337 8.337c.75.75.75 1.972-.001 2.723zM14.195 9.76c.094.173.142.399.142.678s-.047.505-.142.678c-.095.173-.22.306-.376.401a1.485 1.485 0 0 1-.542.191 4.033 4.033 0 0 1-.641.049h-1.504V9.119h1.504c.222 0 .435.017.641.049.205.033.386.097.542.191.156.095.281.228.376.401zm7.062 1.319L12.92 2.742c-.245-.245-.572-.381-.92-.381s-.675.135-.921.381l-8.337 8.337c-.245.246-.381.573-.381.921s.135.675.381.921l8.337 8.337a1.304 1.304 0 0 0 1.842 0l8.337-8.337a1.305 1.305 0 0 0-.001-1.842zm-5.213.4a2.437 2.437 0 0 1-.53.906 2.624 2.624 0 0 1-.943.635c-.386.16-.855.24-1.405.24h-2.034v3.155H9.197v-8.8h3.969c.55 0 1.019.08 1.405.24.386.16.7.372.943.635.242.263.419.563.53.9.111.337.166.686.166 1.048 0 .353-.055.7-.166 1.041z
```

- Commands in path:
  - q: NO
  - Q: NO
  - t: NO
  - T: NO
  - c: YES
  - C: NO
- `svg-path-bounding-box`:
  - minX: 0.0035476024103427706
  - maxX: 23.99973024847777
  - minY: 0.0002697515222243041
  - maxY: 23.999316024364607
  - centerX: 12.002
  - centerY: 12
- `svg-path-bbox`:
  - minX: 0.0006839756353889392
  - maxX: 23.99973024847777
  - minY: 0.0002697515222243041
  - maxY: 23.999316024364607
  - centerX: 12
  - centerY: 12

+ `svgpathtools`
  + minX: 0.0006839756353889115
  + maxX: 23.99973024847777
  + minY: 0.00026975152222386
  + maxY: 23.99931602436461
  + centerX: 12.0
  + centerY: 12.0
+ `github.com/kpym/SVGPathy`
  + minX: 0.000684
  + maxX: 23.9997302
  + minY: 0.0002698
  + maxY: 23.999316
  + centerX: 12
  + centerY: 12


### rstudio.svg

```svg
M12.178.002a12.002 12.002 0 0 0-8.662 3.515 12.002 12.002 0 0 0 0 16.97 12.002 12.002 0 0 0 16.97 0 12.002 12.002 0 0 0 0-16.97A12.002 12.002 0 0 0 12.179.002zM7.77 5.995c.562.128 1.05.217 1.663.217.921 0 1.863-.217 2.786-.217 1.79 0 3.45.814 3.45 2.8 0 1.54-.921 2.517-2.35 2.93l2.788 4.107h1.301v1.01h-1.986l-3.293-4.934h-1.757v3.924h1.718v1.01H7.77v-1.01h1.483V7.134L7.77 6.951v-.957zm4.466 1.012c-.596 0-1.213.053-1.864.127v3.798l.941.02c2.298.034 3.183-.85 3.183-2.026 0-1.376-.997-1.919-2.26-1.919z
```

- Open pull request: #3932

- Commands in path:
  - q: NO
  - Q: NO
  - t: NO
  - T: NO
  - c: YES
  - C: NO
- `svg-path-bounding-box`:
  - minX: 0.07409714635287423
  - maxX: 23.9996091630981
  - minY: 0.0007318976900466973
  - maxY: 24.000609163098105
  - centerX: 12.037
  - centerY: 12.001
- `svg-path-bbox`:
  - minX: 0.00239083690189279
  - maxX: 23.999609163098103
  - minY: 0.0007318976900466971
  - maxY: 24.000609163098105
  - centerX: 12.001
  - centerY: 12.001

+ `svgpathtools`
  + minX: 0.002390836901893678
  + maxX: 23.999609163098103
  + minY: 0.0007336715754888701
  + maxY: 24.000609163098105
  + centerX: 12.001
  + centerY: 12.001
+ `github.com/kpym/SVGPathy`
  + minX: 0.0023908
  + maxX: 23.9996092
  + minY: 0.0007319
  + maxY: 24.0006092
  + centerX: 12.001
  + centerY: 12.001



### sellfy.svg

```svg
M23.179.818C15.533-.273 8.406-.273.8.818-.266 8.377-.266 15.424.8 22.946 4.511 23.491 8.22 24 12.005 24c3.748 0 7.459-.51 11.17-1.017 1.1-7.56 1.1-14.607 0-22.165h.004zm-11.54 18.314c-2.055 0-4.226-.689-5.179-1.199l.807-3.126c1.064.705 2.682 1.395 4.446 1.395 1.395 0 2.24-.436 2.24-1.305 0-.615-.435-.975-1.575-1.26l-2.279-.631c-2.416-.66-3.557-1.891-3.557-3.855 0-2.365 1.83-4.256 5.619-4.256 1.99 0 3.973.545 5.07 1.092l-.951 2.976c-1.104-.615-2.79-1.125-4.226-1.125-1.365 0-1.95.436-1.95 1.092 0 .619.404.87 1.291 1.092l2.488.734c2.566.736 3.707 1.966 3.707 3.885-.076 2.701-2.461 4.517-5.957 4.517l.006-.026z
```

- Open pull request: #3937

- Commands in path:
  - q: NO
  - Q: NO
  - t: NO
  - T: NO
  - c: YES
  - C: YES
- `svg-path-bounding-box`:
  - minX: 0.0005000000000000004
  - maxX: 24
  - minY: 0.818
  - maxY: 24
  - centerX: 12
  - centerY: 12.409
- `svg-path-bbox`:
  - minX: 0.0005000000000000004
  - maxX: 24
  - minY: -0.000250000000000028
  - maxY: 24
  - centerX: 12
  - centerY: 12

+ `svgpathtools`
  + minX: 0.0004999999999999449
  + maxX: 23.179000000000002
  + minY: -0.00024999999999997247
  + maxY: 24.0
  + centerX: 11.59
  + centerY: 12.0
+ `github.com/kpym/SVGPathy`
  + minX: 0.0005
  + maxX: 24
  + minY: -0.00025
  + maxY: 24
  + centerX: 12
  + centerY: 12


### squarespace.svg

```svg
M22.655 8.719c-1.802-1.801-4.726-1.801-6.564 0l-7.351 7.35c-.45.45-.45 1.2 0 1.65.45.449 1.2.449 1.65 0l7.351-7.351c.899-.899 2.362-.899 3.264 0 .9.9.9 2.364 0 3.264l-7.239 7.239c.9.899 2.362.899 3.263 0l5.589-5.589c1.836-1.838 1.836-4.763.037-6.563zm-2.475 2.437c-.451-.45-1.201-.45-1.65 0l-7.354 7.389c-.9.899-2.361.899-3.262 0-.45-.45-1.2-.45-1.65 0s-.45 1.2 0 1.649c1.801 1.801 4.726 1.801 6.564 0l7.351-7.35c.449-.487.449-1.239.001-1.688zm-2.439-7.35c-1.801-1.801-4.726-1.801-6.564 0l-7.351 7.351c-.45.449-.45 1.199 0 1.649s1.2.45 1.65 0l7.395-7.351c.9-.899 2.371-.899 3.27 0 .451.45 1.201.45 1.65 0 .421-.487.421-1.199-.029-1.649h-.021zm-2.475 2.437c-.45-.45-1.2-.45-1.65 0l-7.351 7.389c-.899.9-2.363.9-3.265 0-.9-.899-.9-2.363 0-3.264l7.239-7.239c-.9-.9-2.362-.9-3.263 0L1.35 8.719c-1.8 1.8-1.8 4.725 0 6.563 1.801 1.801 4.725 1.801 6.564 0l7.35-7.351c.451-.488.451-1.238 0-1.688h.002z
```

- Commands in path:
  - q: NO
  - Q: NO
  - t: NO
  - T: NO
  - c: YES
  - C: NO
- `svg-path-bounding-box`:
  - minX: 1.35
  - maxX: 23.999660308381387
  - minY: 2.453999999999999
  - maxY: 21.54525
  - centerX: 12.675
  - centerY: 12
- `svg-path-bbox`:
  - minX: 5.551115123125783e-17
  - maxX: 23.999660308381387
  - minY: 2.453999999999999
  - maxY: 21.54525
  - centerX: 12
  - centerY: 12

+ `svgpathtools`
  + minX: 1.35
  + maxX: 23.99966030838139
  + minY: 2.453999999999999
  + maxY: 21.3766875
  + centerX: 12.675
  + centerY: 11.915
+ `github.com/kpym/SVGPathy`
  + minX: 0
  + maxX: 23.9996603
  + minY: 2.454
  + maxY: 21.54525
  + centerX: 12
  + centerY: 12

### newyorktimes.svg

```svg
M21.272,14.815h-0.098c-0.747,2.049-2.335,3.681-4.363,4.483v-4.483l2.444-2.182l-2.444-2.182V7.397 c2.138,0.006,3.885-1.703,3.927-3.84c0-2.629-2.509-3.556-3.927-3.556c-0.367-0.007-0.734,0.033-1.091,0.12v0.131h0.556 c0.801-0.141,1.565,0.394,1.706,1.195C17.99,1.491,17.996,1.537,18,1.583c-0.033,0.789-0.7,1.401-1.488,1.367 c-0.02-0.001-0.041-0.002-0.061-0.004c-2.444,0-5.323-1.985-8.454-1.985C5.547,0.83,3.448,2.692,3.284,5.139 C3.208,6.671,4.258,8.031,5.76,8.346v-0.12C5.301,7.931,5.041,7.407,5.084,6.862c0.074-1.015,0.957-1.779,1.973-1.705 C7.068,5.159,7.08,5.16,7.091,5.161c2.629,0,6.872,2.182,9.501,2.182h0.098v3.142l-2.444,2.182l2.444,2.182v4.549 c-0.978,0.322-2.003,0.481-3.033,0.469c-1.673,0.084-3.318-0.456-4.614-1.516l4.429-1.985V7.451l-6.196,2.727 c0.592-1.75,1.895-3.168,3.589-3.905V6.175c-4.516,1.004-8.138,4.243-8.138,8.705c0,5.193,4.025,9.12,9.818,9.12 c6.011,0,8.727-4.363,8.727-8.814V14.815z M8.858,18.186c-1.363-1.362-2.091-3.235-2.007-5.16c-0.016-0.88,0.109-1.756,0.371-2.596 l2.051-0.938v8.476L8.858,18.186z
```

- Open pull request: #4109

- Commands in path:
  - q: NO
  - Q: NO
  - t: NO
  - T: NO
  - c: YES
  - C: YES
- `svg-path-bounding-box`:
  - minX: 2.7270000000000003
  - maxX: 21.272
  - minY: 0.001000000000000334
  - maxY: 24
  - centerX: 11.999
  - centerY: 12.001
- `svg-path-bbox`:
  - minX: 2.7270000000000003
  - maxX: 21.272
  - minY: 0.00021808510638331277
  - maxY: 24
  - centerX: 11.999
  - centerY: 12

+ `svgpathtools`
  + minX: 2.7270000000000003
  + maxX: 21.272
  + minY: 0.001000000000000334
  + maxY: 24.0
  + centerX: 11.999
  + centerY: 12.001
+ `github.com/kpym/SVGPathy`
  + minX: 2.727
  + maxX: 21.272
  + minY: 0.0002181
  + maxY: 24
  + centerX: 11.999
  + centerY: 12

---

## Icons that must be corrected now but not before

### treehouse.svg

```svg
M20.537 4.118c-.806-.453-2.092.278-2.871 1.635L16.25 8.215a3.104 3.104 0 0 0 .21 3.18l.041.062c.653.94 1.535 1.808 1.823 2.118a1.613 1.613 0 0 1-.739 2.654 1.603 1.603 0 0 1-2.025-1.747c.045-.35-.067-.927-.574-1.489-.506-.563-1.54.5-1.874 1.61l-.016.061c-.334 1.094-.546 2.05-.482 2.143.037.06.072.12.105.182a1.81 1.81 0 0 1-3.196 1.701 1.806 1.806 0 0 1 .747-2.446l.121-.061c.065-.03.26-.486.423-1.032l.301-.987c.019-.047.033-.107.045-.168l.897-3.19-.957 1.96c-.112-.363-.3-.38-.709-.091-.243.183-.653.531-.85.669-.365.273-.685.788-.851 1.109a1.313 1.313 0 0 1-.41.5c-.684.564-1.687.456-2.234-.227a1.591 1.591 0 0 1 .912-2.552c.409-.092 1.777-.927 2.596-1.52.152-.106.274-.197.38-.304l2.203-1.67-1.914 1.032s-.196-.016-.426.017c-.698.075-1.428.182-1.564.35a.999.999 0 0 1-.29.272c-.637.456-1.519.32-1.989-.317A1.437 1.437 0 0 1 6.29 8.04c.259-.183.577-.274.865-.274.518.016 1.87.29 2.993.092l.288-.045c1.14-.196 2.476-1.186 3.024-2.187l1.184-2.067c.653-1.139.608-2.384-.105-2.795l-1.323-.76c-.653-.363-1.715-.363-2.354 0L2.004 4.97C1.337 5.319.805 6.23.805 6.975v9.744c0 .744.532 1.656 1.178 2.02l8.85 4.983c.652.365 1.716.365 2.354 0l8.826-4.983c.653-.368 1.184-1.276 1.184-2.02v-9.76c0-.744-.531-1.653-1.169-2.02l-1.46-.823
```

- Commands in path:
  - q: NO
  - Q: NO
  - t: NO
  - T: NO
  - c: YES
  - C: YES
- `svg-path-bounding-box`:
  - minX: 0.805
  - maxX: 23.197000000000003
  - minY: 0.003999999999999337
  - maxY: 23.99575
  - centerX: 12.001
  - centerY: 12
- `svg-path-bbox`:
  - minX: 0.805
  - maxX: 23.197000000000003
  - minY: -0.2682500000000007
  - maxY: 23.99575
  - centerX: 12.001
  - centerY: 11.864

+ `svgpathtools`
  + minX: 0.8049999999999986
  + maxX: 23.197000000000006
  + minY: -0.26825000000000065
  + maxY: 23.99575
  + centerX: 12.001
  + centerY: 11.864
+ `github.com/kpym/SVGPathy`
  + minX: 0.805
  + maxX: 23.197
  + minY: -0.26825
  + maxY: 23.99575
  + centerX: 12.001
  + centerY: 11.864

**Comment by mondeja** [comment]
> As soon as this gets merged, I'll push "my" failed icons again. Hopefully then they will pass.

I think that simply those icons (at least most of them) should not be corrected at all, like microsoft ones. See my previous comment for a complete list. So some of your pulls should be closed.

**Comment by mondeja** [comment]
This is the new list that will replace #3169:

## Icons that don't fit the canvas (#3107)

- [x] 500px - #3312
- [x] ABB RobotStudio - #3961
- [x] Accusoft - #3751
- [x] Airbnb - #3874
- [x] Airbus - #3962
- [x] AirPlay Audio - #3963 
- [x] Amazon - #3619
- [x] Amazon Lumberyard - #3964 
- [x] Anaconda - #3965 
- [x] Android Studio - #3802
- [x] AngelList - #3966
- [x] Angular - #3814
- [x] Apache - #3967 
- [x] Apache Cassandra - #3968
- [x] Apache OpenOffice - #3969 
- [x] Apple - #3970 
- [x] Apple Music - #3971 
- [x] Apple Pay - #3972 
- [x] ARCHICAD - #3327
- ~~arXiv - #3973~~ 
- [x] AT&T - #3980
- [x] Atlassian - #3872
- [x] Audiomack - #3981
- [x] Automatic - #3982
- [x] Awesome Lists - #3783 
- [x] Azure Functions - #3983
- [x] Baidu - #3984
- [x] Bamboo - #3992
- [x] Bath ASU - #3993
- [x] Beatport - #3994
- [x] Beats - #3995
- [x] Beats by Dre - #3996
- [x] Behance - #3997
- [x] Bitrise - #3998
- [x] BMC Software - #3999
- [x] Boeing - #4000
- [x] Boost - #4001
- [x] Brand.ai - #4002
- [x] Buddy - #4003
- [x] Buffer - #4004
- [x] C - #3868
- [x] Cinema 4D - #4005
- [x] Cirrus CI - #4006
- [x] CloudBees - #4007
- [x] Clyp - #4008
- [x] CodeChef - #4009
- [x] Codecov - #3642
- [x] CodeIgniter - #4010
- [x] Codeship - #4011
- [x] Codewars - #4012
- [x] CoffeeScript - #3737
- [x] Common Workflow Language - #4013
- [x] Composer - #4014
- [x] ComproPago - #4015
- [x] Coursera - #4016
- [x] C++ - #3869
- [x] CSS Wizardry - #4017
- [x] curl - #3818 
- [x] Dash - #4018
- [x] Dassault Systèmes - #4019
- [x] Datadog - #4020
- [x] dblp - #4021
- [x] Debian - #3809
- [x] Deno - #3738
- [x] Dependabot - #4022
- [x] Diaspora - #4023
- [x] Disroot - #4024
- [x] Django - #3739
- [x] DLNA - #4025
- [x] Draugiem.lv - #4026
- [x] Drupal - #4027
- [x] Dunked - #4028
- [x] Dynatrace - #4029
- [x] Eclipse IDE - #3803
- [x] Elastic - #4030
- [x] Elastic Cloud - #4031
- [x] Elasticsearch - #4032
- [x] Elastic Stack - #4033
- [x] Electron - #4034
- [x] Elixir - #4035
- ~~Emlakjet - #4036~~
- [x] Empire Kred - #4037
- [x] Envato - #4038
- [x] Eventbrite - #4039
- [x] EVRY - #4040
- [x] F-Secure - #4041
- [x] Facebook - #3856
- [x] FACEIT - #4042
- [x] Fandom - #4043
- [x] Favro - #4044
- [x] FeatHub - #4045
- [x] Fedora - #3656
- [x] FedRAMP - #4046
- [x] Feedly - #4047
- [x] Ferrari - #3759
- [x] FileZilla - #4048
- [x] Firebase - #3620
- [x] Firefox Browser - #3622
- [x] Flask - #3740
- [x] Flutter - #3627
- [x] freedesktop.org - #4049
- [x] Fur Affinity - #2979
- [x] Gatsby - #3848
- [x] Genius - #4050
- [x] Gentoo - #3810
- [x] GIMP - #4051
- [x] Gitea - #4052
- [x] GitLab - #3621
- [x] Glitch - #4053
- [x] GNOME - #3811
- [x] GNU - #3866
- [x] GNU IceCat - #4054
- [x] Godot Engine - #4055
- [x] GoldenLine - #4056
- [x] Goodreads - #4057
- [x] Google Cardboard - #4058
- [x] Google Nearby - #4059
- [x] GOV.UK - #4060
- [x] Gradle - #4061
- [x] Grafana - #4062
- [x] GreenSock - #4063
- [x] Gumtree - #4064
- [x] HackerEarth - #4065
- [x] Haskell - #4066
- [x] Helm - #4067
- [x] HERE - #4068
- [x] Hexo - #4069
- [x] homify - #4070
- [x] Honda - #3760
- [x] Huawei - #3826
- [x] HubSpot - #3625
- [x] Hulu - #3832
- [x] Humble Bundle - #4071
- [x] Iata - #4072
- [x] iCloud - #4073
- [x] ICON - #4074
- [x] ICQ - #4075
- [x] Indeed - #4076
- [x] Itch.io - #4077
- [x] iTunes - #3833
- [x] Jenkins - #3749
- [x] Jinja - #4078
- [x] jQuery - #3815
- [x] JSON - #3643
- [x] Jupyter - #3170
- [x] Just Eat - #3390
- [x] KaiOS - #4079
- [x] Kentico - #4080
- [x] Keybase - #4081
- [x] Kibana - #4082
- [x] Laravel - #3849
- [x] Last.fm - #4083
- [x] LaTeX - #3865
- [x] LeetCode - #4084
- [x] LG - #3827
- [x] LibraryThing - #4085
- [x] LineageOS - #4086
- [x] Linode - #4087
- [x] Linux - #3657
- [x] LLVM - #4088
- [x] Lumen - #3850
- [x] Magisk - #4096 
- [x] Mail.Ru - #4097 
- [x] Markdown - #3643
- [x] Mastodon - #4098 
- [x] Mathworks - #4099 
- [x] McAfee - #4100 
- [x] Meetup - #4101 
- [x] Mendeley - #4102 
- [x] Messenger - #3857
- [x] Microsoft Office - #4103 
- [x] MicroStrategy - #4104 
- [x] Minds  - #4105 
- [x] Mixer  - #4106 
- [x] Myspace - #3858
- [x] NEC  - #4107 
- [x] Netflix - #3669
- [x] Netlify - #4108 
- ~~New York Times - #4109~~ 
- [x] Next.js - #3688
- [x] Nextdoor - #4110 
- [x] NFC - #4111 
- [x] Nintendo GameCube - #3774
- [x] Nokia - #3828
- [x] Notist - #4112 
- [x] NuGet - #4113 
- [x] Nutanix - #4114 
- [x] Nuxt.js - #3687
- [ ] OCaml
- [ ] Octave
- [ ] Odnoklassniki
- [ ] Open Access
- [ ] Open Collective
- [ ] Origin
- [ ] Overleaf
- [ ] Palo Alto Software
- [ ] Pantheon
- [ ] Parse.ly
- [x] Pastebin - #3786 
- [ ] Patreon
- [ ] Pi-hole
- [ ] Piwigo
- [ ] Platzi
- [x] PlayStation - #3775
- [x] PlayStation 3 - #3776
- [x] PlayStation 4 - #3777
- [ ] Plurk
- ~~pre-commit~~
- [ ] Prismic
- [ ] protocols.io
- [ ] ProtonMail
- [ ] PureScript
- [x] PyTorch - #3819 
- [ ] Quarkus
- [ ] Quest
- [ ] Qzone
- [ ] RadioPublic
- [ ] Read the Docs
- [ ] Reason Studios
- [x] Redux - #3742
- [ ] Renren
- [ ] Rhinoceros
- [ ] Riseup
- [x] rollup.js - #3685
- [x] Ruby on Rails - #3686
- [ ] Runkeeper
- [x] Rust - #3820
- [ ] Salesforce
- [ ] Sat.1
- [ ] Sentry
- [ ] Siemens
- [ ] Skillshare
- [ ] Socket.io
- [ ] SonarLint
- [ ] SonicWall
- [ ] Source Engine
- [ ] SparkFun
- [ ] Spring
- [ ] Sprint
- ~~Squarespace~~
- [ ] Stackbit
- [ ] StackPath
- [ ] Statamic
- [ ] Staticman
- [ ] Steem
- [ ] Steemit
- [ ] Steinberg
- [ ] Storify
- [x] Storybook - #3746
- [x] Strapi - #3747
- [ ] strongSwan
- [ ] Stylus
- [ ] Sublime Text
- [ ] Super User
- [ ] Svelte
- [ ] Swarm
- [ ] Synology
- [ ] Telegram
- [ ] Tencent Weibo
- [ ] Terraform
- [ ] The Register
- [ ] Threema
- [ ] Topcoder
- [ ] TrainerRoad
- [x] Travis CI- #3748
- [ ] Treehouse
- [x] Twitter - #3860
- [x] Ubisoft - #3778 
- [ ] Udacity
- [x] Udemy - #3877
- [ ] Vagrant
- [ ] Veeam
- [x] Vimeo - #3668
- [x] Vine - #3835
- [x] Visual Studio - #3805
- [ ] VLC media player
- [ ] Vulkan
- [ ] webcomponents.org
- [ ] Webmin
- [x] Webpack - #3683
- [ ] WeChat
- [ ] Windows 95
- [ ] Wolfram Language
- [ ] X-Pack
- [ ] XAML
- [x] Xcode - #3806
- [ ] XFCE
- [ ] Yelp
- [x] YouTube - #3667
- [x] Zoom - #3666

## Icons with outlying precision levels (#3120)
- [x] Jupyter (17) - #3170
- [ ] Highly (15)
- [x] Audio-Technica (8) - #3885
- [x] GitKraken (8) - #3745
- [x] Ruby on Rails (8) - #3686
- [ ] TUI (8)
- [x] Arch Linux (6) - #3808
- [ ] Autodesk (6)
- [x] Code Climate (6) - #3892
- [ ] YouTube Music (6)
- ~~Bitrise (1)~~
- ~~CEVO (1)~~
- ~~Craft CMS (1)~~
- ~~Eventbrite (1)~~
- ~~FACEIT (1)~~
- ~~Flipboard (1)~~
- ~~Gitpod (1)~~
- ~~Gradle (1)~~
- ~~HP (1)~~
- ~~JetBrains (1)~~
- ~~Kentico (1)~~
- ~~Known (1)~~
- ~~Koding (1)~~
- ~~Kotlin (1)~~
- ~~Linux Foundation (1)~~
- ~~Logstash (1)~~
- ~~Material Design Icons (1)~~
- ~~Micro.blog (1)~~
- ~~Microsoft (1)~~
- ~~Roundcube (1)~~
- ~~TensorFlow (1)~~
- ~~Unity (1)~~
- ~~Xcode - #3806~~
- ~~Delicious (0)~~
- ~~Discover (0) - #3311~~
- ~~Figma (0)~~
- ~~Framer (0)~~
- ~~PeerTube (0)~~

## Icons that are not centred on the canvas (#3250)
- [x] About.me - #3883
- [x] Android - #3658
- [x] AppSignal - #3873 
- [x] Atom - #3884
- [x] Audio-Technica - #3885
- [x] Azure DevOps - #3886
- [x] Bitbucket - #3887
- [x] Bower - #3888
- [x] Cash App - #3889
- [x] Clockify - #3890
- [x] Codecademy - #3891
- [x] Code Climate - #3892
- [x] CodeFactor - #3893
- [x] CodeSandbox - #3784
- [x] CRYENGINE - #3894
- [x] Dashlane - #3895
- [x] DTube - #3896
- [x] eBay - #3875
- [x] Eleventy - #3897
- [x] ESEA - #3898
- [x] Etsy - #3876
- [x] Evernote - #3899
- [x] EyeEm - #3900
- [x] Go - #3816
- [x] Google My Business - #3901
- [x] Google Podcasts - #3902
- [x] Google Tag Manager - #3903
- [x] Gutenberg - #3904
- [x] HappyCow - #3905
- [x] HelloFresh - #3907
- [x] Hypothesis - #3908
- [x] IconJar - #3909
- [x] Kaspersky - #3910
- [x] KeyCDN - #3911
- [x] Koding - #3912
- [x] Livestream - #3913
- [x] MailChimp - #3914
- [x] Mercedes - #3761
- ~~Microsoft Excel - #3915~~
- ~~Microsoft Exchange - #3916~~
- ~~Microsoft OneDrive - #3917~~
- ~~Microsoft Outlook - #3918~~
- ~~Microsoft OneNote - #3919~~
- ~~Microsoft Word - #3920~~
- [x] Mix - #3921
- [x] MongoDB - #3754
- [x] Monzo - #3922
- [x] MySQL - #3755
- [x] Nim - #3923
- [x] OpenID - #3924
- [x] Open Source Initiative - #3925
- [x] OpenVPN - #3926
- [x] Pepsi - #3878
- [x] PostgreSQL - #3756
- [x] PowerShell - #3804
- [x] Python - #3741
- [x] Qi - #3927
- [x] Qiita - #3928
- [x] QuickTime - #3834
- [x] Quasar - #3929
- [x] Realm - #3930
- [x] Riot - #3931
- ~~RStudio - #3932~~
- [x] RunKit - #3933
- [x] Scaleway - #3934
- [x] Scrutinizer CI - #3935
- [x] Seagate - #3936
- ~~Sellfy - #3937~~
- [x] Slackware - #3938
- [x] SlideShare - #3939
- [x] Sourcegraph - #3940
- [x] TELE5 - #3941
- [x] TikTok - #3859
- [x] TuneIn - #3942
- [ ] Treehouse
- [x] Trove - #3943
- [x] Vauxhall - #3944
- [x] Vultr - #3870
- [x] WebAuthn - #3945
- [x] write.as - #3946
- [x] Zalando - #3947
- [x] ZDF - #3948

**Review by service-paradis — APPROVED** [review]
LGTM! Good job on the comparison with other tools! 💯

**Comment by mondeja** [comment]
Thank you for your review @service-paradis :+1: Since everyone agrees, I perform the merge.
